title: Sun Lab
email: ws467@cornell.edu
description: >- # this means to ignore newlines until "baseurl:"
  Sun Lab - NeuroAI Research at Cornell University
baseurl: "/sunlab" # the subpath of your site, e.g. /blog
url: "https://neuroai.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: neuroai

# Build settings
plugins:
  - jekyll-feed

sass:
  style: compressed
